### PR TITLE
upgrade to anchor 0.26

### PR DESCRIPTION
**Pull request by dovahcrow**

### CODE REVIEW

**Comment by odcheung** [comment]
hey @dovahcrow, just to give you a heads up that we are looking into upgrading the anchor version. We need to do our due diligence on our side to make sure it's safe (since it's not a simple update) and there are some breaking SDK changes that come along with it (ex. provider changes). So it might take some time.

**Comment by dovahcrow** [comment]
Hi @odcheung yeah, I totally understand. It is not easy to change even a tiny bit of the code in the smart contract space, not to mention a dependency upgrade.

**Comment by dovahcrow** [comment]
The mpl dependency is using my git fork because they haven't upgraded to Solana 1.10/anchor 0.25 as well. I'll change that once they upgrade.

**Comment by rawfalafel** [comment]
hey @dovahcrow , thanks for putting up this PR! is it possible to upgrade without a forked version of `mpl-token-metadata` at this point? do we have other options?

**Comment by dovahcrow** [comment]
@rawfalafel done

**Comment by rawfalafel** [comment]
thanks! i will take a look

**Comment by yugure-orca** [comment]
@dovahcrow ( cc: @rawfalafel )
Hi! Thanks for this PR. 🙏

I would like to commit some updates and test case changes, is that ok?

Also, if possible, we would like to request the following two changes.

### 1. how to fix Err(ErrorCode::xxxx) compile error

Many parts of the existing code, Err(ErrorCode::xxxxxx.into()) is used.
Could you change the use of "?" operator to "Err(ErrorCode::xxxxxx.into())"?

e.g.
```
return Err(ErrorCode::InvalidTickArraySequence);
-->
return Err(ErrorCode::InvalidTickArraySequence.into());

u64::try_from(t).or(Err(ErrorCode::InvalidTimestampConversion))
-->
u64::try_from(t).or(Err(ErrorCode::InvalidTimestampConversion.into()))
```

### 2. revert changes to SwapTickSequence::new if it is not essential

We noticed that the code related with SwapTickSequence::new has been changed.
Let us know any reason why this change is necessary?
We are cautious about changing proven code.
If there is no essential reason, we would like to revert back to the original.

- https://github.com/orca-so/whirlpools/pull/34/files#diff-b5b6caf797a24db9effac8a8642bd8d8ea2032dd43aa4080de3d5ffb44bc7dbaR11
- https://github.com/orca-so/whirlpools/pull/34/files#diff-0a484cfeb6d63bdcaab68c9cb7e055e058622bf23e4b582ac9523b5cabbbde41R61
- https://github.com/orca-so/whirlpools/pull/34/files#diff-b38b7cb1424359370330db5ccf84246a54296984fe79919724a6190e197a3b19R108

Thanks.

**Comment by dovahcrow** [comment]
Sure push what ever commit you would like. I will revert these later this week.

**Comment by yugure-orca** [comment]
@dovahcrow 
I have added the commits I want to add, could you make your commits ? 🙏
I would like to add an commit related to tests including SwapTickSequence::new after your modifications.
Thanks!

**Comment by dovahcrow** [comment]
@yugure-orca done. Could you please take a look again?

**Comment by yugure-orca** [comment]
@dovahcrow 
Thanks! LGTM🙂
A third-party audit is scheduled and is expected to be merged after the audit.👍

**Comment by yugure-orca** [comment]
@dovahcrow 
All your commits included in this PR have been audited and merged as the base of [PR#89](https://github.com/orca-so/whirlpools/pull/89).
I'll close this PR in a few days.
Very thanks for your work! 🙌

**Comment by odcheung** [comment]
closing this as the patch has been merged in #89.

**Pull request closed without merging**
